# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-10-20 15:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangocms_slick_slider', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='slicksliderimage',
            name='link_target',
            field=models.BooleanField(default=True, help_text='open link in new window', verbose_name='image link target'),
        ),
    ]
