# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-10-12 15:44
from __future__ import unicode_literals

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('djangocms_slick_slider', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='slickslider',
            name='slick_settings',
            field=models.TextField(default='\\{\\}', verbose_name='Slick settings'),
        ),
        migrations.AlterField(
            model_name='slickslider',
            name='settings',
            field=jsonfield.fields.JSONField(verbose_name='Slick settings'),
        ),
    ]
