# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-02-01 19:50
from __future__ import unicode_literals

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('djangocms_slick_slider', '0002_slicksliderimage_link_target'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='slickslider',
            options={'verbose_name': 'slick slider', 'verbose_name_plural': 'slick sliders'},
        ),
        migrations.AlterField(
            model_name='slickslider',
            name='arrow_color',
            field=models.CharField(default='#666', help_text='Define the color of slider arrows here. All CSS color values work (e.g. #efefef).', max_length=255, verbose_name='arrow color'),
        ),
        migrations.AlterField(
            model_name='slickslider',
            name='settings',
            field=jsonfield.fields.JSONField(blank=True, null=True, help_text='Check <a href="http://kenwheeler.github.io/slick/" target="_blank">Slick Documentation</a> for possible settings <br>Use JSON format and check the errors in the editor<br>You can also use online JSON validators', verbose_name='slick settings'),
        ),
        migrations.AlterField(
            model_name='slickslider',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='slider title'),
        ),
    ]
