# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-10-12 15:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangocms_slick_slider', '0002_auto_20171012_1744'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slickslider',
            name='slick_settings',
        ),
    ]
