# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2019-12-02 16:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangocms_slick_slider', '0003_auto_20180201_2050'),
    ]

    operations = [
        migrations.AddField(
            model_name='slickslider',
            name='full_width',
            field=models.BooleanField(default=False, verbose_name='full width'),
        ),
        migrations.AddField(
            model_name='slickslider',
            name='image_max_width',
            field=models.IntegerField(blank=True, help_text='Define max height of the slider.', null=True, verbose_name='max. width'),
        ),
        migrations.AddField(
            model_name='slickslider',
            name='slider_max_height',
            field=models.IntegerField(blank=True, help_text='Define max height of the slider.', null=True, verbose_name='max. height'),
        ),
    ]
