# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-02-01 19:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangocms_slick_slider', '0004_auto_20180201_1955'),
    ]

    operations = []
