# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-02-01 19:09
from __future__ import unicode_literals

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('djangocms_slick_slider', '0004_auto_20180201_1955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slickslider',
            name='settings',
            field=jsonfield.fields.JSONField(blank=True, help_text='Check <a href="http://kenwheeler.github.io/slick/" target="_blank">Slick Documentation</a> for possible settings <br>Use JSON format and check the errors in the editor<br>You can also use online JSON validators', verbose_name='slick settings'),
        ),
    ]
