# Generated by Django 3.1.6 on 2021-05-03 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangocms_slick_slider', '0005_auto_20210213_1708'),
    ]

    operations = [
        migrations.AddField(
            model_name='slickslider',
            name='lazy_load_images',
            field=models.BooleanField(default=True, help_text='Set to true if images should load lazily.', verbose_name='lazy load images'),
        ),
    ]
